parameters:

    ccdn_user_user.user.repository.class:           CCDNUser\UserBundle\Repository\UserRepository

    ccdn_user_user.user.manager.class:              CCDNUser\UserBundle\Manager\UserManager

    ccdn_user_user.registration.form.type:          CCDNUser\UserBundle\Form\Type\RegistrationFormType

    ccdn_user_user.dashboard.integrator.class:      CCDNUser\UserBundle\Component\Dashboard\DashboardIntegrator

services:

    #
    # Repositories.
    #
    ccdn_user_user.user.repository:
        class: %ccdn_user_user.user.repository.class%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'CCDNUser\UserBundle\Entity\User'

    #
    # Managers.
    #
    ccdn_user_user.user.manager:
        class: %ccdn_user_user.user.manager.class%
        arguments:  [@doctrine, @service_container]

    #
    # Registration Forms.
    #
    ccdn_user_user.registration.form.type:
        class: %ccdn_user_user.registration.form.type%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ccdn_user_registration }

    #
    # Dashboard Integrator.
    #
    ccdn_user_user.dashboard.integrator:
        class: %ccdn_user_user.dashboard.integrator.class%
        arguments: [@service_container]
        tags:
            - { name: ccdn_component_dashboard.integrator }
